#    _____            _       __   _  __
#   / ___/____  _____(_)___ _/ /  | |/ /
#   \__ \/ __ \/ ___/ / __ `/ /   |   /
#  ___/ / /_/ / /__/ / /_/ / /   /   |
# /____/\____/\___/_/\__,_/_/   /_/|_|
#
# Plugin Developed By GX_Regent-2.0 & Sgattix
# Main Config
#
# Version: 1.0.0-Alpha

License: "Your-License-Here"

YoutubeChannel: "https://youtube.com/example"
TwitchChannel: "https://twitch.tv/example"
TikTokChannel: "https://tiktok.com/example"
WebsiteLink: "https://www.example.com/"
StoreLink: "https://store.example.com/"
DiscordLink: "https://discord.example.com/"

youtube: true
twitch: true
tiktok: true
website: true
store: true
discord: true

debug: false