#    _____            _       __   _  __
#   / ___/____  _____(_)___ _/ /  | |/ /
#   \__ \/ __ \/ ___/ / __ `/ /   |   /
#  ___/ / /_/ / /__/ / /_/ / /   /   |
# /____/\____/\___/_/\__,_/_/   /_/|_|
#
# Plugin Developed By GX_Regent-2.0 & Sgattix
# Main Config
#
# Version: 1.0.0-Alpha

YoutubeChannel: "https://youtube.com/example"
TwitchChannel: "https://twitch.tv/example"




debug: false